name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
 
  build_physimess:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build PhysiMeSS project
      run: |
        make physimess-sample
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiMeSS project
      run: |
        ./project
        ./project config/Fibre_Initialisation/mymodel_initialisation.xml
        ./project config/Cell_Fibre_Mechanics/mymodel_rotating.xml
        ./project config/Fibre_Degradation/mymodel_matrix_degradation.xml
        