name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build PhysiMeSS project
      run: |
        make physimess-sample
        make clean
        make
        
    - name: Run PhysiMeSS project
      run: |
        ./project
        ./project config/Fibre_Initialisation/mymodel_initialisation.xml
        ./project config/Cell_Fibre_Mechanics/mymodel_rotating.xml
        ./project config/Fibre_Degradation/mymodel_matrix_degradation.xml
